pipeline {
	parameters{
		string(name :'environment', defaultValue :'Terraform', description : 'environemnt name:')
		booleanParam(name:'autoApprove', defaultValue :false, description :'Auto Approval')
	}
	environment{
		AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
		AWS_ACCESS_KEY = credentials('AWS_ACCESS_KEY')
	}
	agent any
	stages{
		stage('GIT'){
			steps {
				git branch: 'main', url: 'https://github.com/Sri-Udaya/EC2_Pipeline.git'
			}
		}
		stage('plan'){
			steps{
				sh 'cd /opt/EC2Instance;terraform init'
				sh 'cd /opt/EC2Instance;terraform plan'
			}
		}
	}
}
